#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Installs Voldemort
#

set -x
set -e

VOLDEMORT_VERSION=${1:-0.90.RC2}
VOLDEMORT_ROOT=/usr/local/voldemort
VOLDEMORT_TAR_URL=http://test.project-voldemort.com:8080/job/release-090/lastSuccessfulBuild/artifact/dist/voldemort-$VOLDEMORT_VERSION.tar.gz
VOLDEMORT_HOME=/var/log/voldemort

v_tar_file=`basename $VOLDEMORT_TAR_URL`

# Download the source
curl="curl --retry 3 --show-error --fail"
for i in `seq 1 3`;
do
  $curl -O $VOLDEMORT_TAR_URL
  if tar zxf $v_tar_file -C /usr/local ; then
    break;
  else
    rm -f $v_tar_file
  fi
done

if [ ! -e $v_tar_file ]; then
  echo "Failed to download $VOLDEMORT_TAR_URL. Aborting."
  exit 1
else
  mv /usr/local/voldemort-$VOLDEMORT_VERSION $VOLDEMORT_ROOT 
fi

# Set Voldemort vars
echo "export VOLDEMORT_ROOT=$VOLDEMORT_ROOT" >> /etc/profile
echo "export VOLDEMORT_HOME=$VOLDEMORT_HOME" >> /etc/profile

mkdir -p $VOLDEMORT_HOME/config

# Copy sample property files over to config dir
cp $VOLDEMORT_ROOT/config/single_node_cluster/config/* $VOLDEMORT_HOME/config/.

# Start
sed -i -e "s/exit 0//" /etc/rc.local
sed -i -e "s/voldemort//" /etc/rc.local
cat >> /etc/rc.local <<EOF
$VOLDEMORT_ROOT/bin/voldemort-server.sh > $VOLDEMORT_HOME/voldemort.log 2>&1 &
EOF

